apiVersion: v2
name: n8n-kubernetes-helmcharts
description: Um Helm chart para deployar n8n, PostgreSQL e Redis no Kubernetes
type: application
version: 0.1.0 # Sua versão do chart agregado
appVersion: "1.46.0" # Versão do n8n que você pretende usar (exemplo, atualize se necessário)

dependencies:
  - name: n8n
    version: "0.33.2" # Ou a versão mais recente do chart n8n que você testou
    repository: "https://helm.n8n.io/"
  - name: postgresql
    version: "14.2.4" # Ou a versão mais recente do chart Bitnami PostgreSQL
    repository: "oci://registry-1.docker.io/bitnamicharts/postgresql"
    condition: postgresql.enabled
  - name: redis
    version: "18.15.1" # Ou a versão mais recente do chart Bitnami Redis
    repository: "oci://registry-1.docker.io/bitnamicharts/redis"
    condition: redis.enabled