# Configurações do subchart n8n
n8n:
  # fullnameOverride: auto546-n8n # Você está setando via comando

  image:
    repository: n8nio/n8n
    tag: "1.46.0" # RECOMENDADO: Use uma tag específica em vez de "latest"
    pullPolicy: IfNotPresent

  replicaCount: 1

  config:
    webhookUrl: "https://n8n.546digitalservices.com" # Obrigatório
    timezone: "America/Sao_Paulo"
    nodeEnv: "production"
    executionsMode: "queue"
    executionsProcess: "main"

    # **MUITO IMPORTANTE:** Use uma chave forte e única. Guarde-a em segurança.
    # Esta chave será usada para criar um Secret, que o deployment.yaml do n8n usará.
    encryptionKey: "1B6kPmysGGoNBKnvGuueJ3222u1zYBOK!"
    # Se você já tiver um secret com a chave de criptografia:
    # existingEncryptionKeySecret: "meu-secret-com-a-encryption-key-do-n8n"
    # encryptionKeySecretKey: "n8n-encryption-key" # Chave dentro do secret existente

    extraEnvVars: []
    # - name: N8N_LOG_LEVEL
    #   value: "debug"

  extraNodePackages:
    - name: "@n8n/n8n-nodes-langchain"
      installArgs:
        - "--no-save"

  configMap: # Para settings.json customizado, se necessário
    enabled: false
    # settings: |
    #   { "someCustomN8nSetting": true }

  service:
    type: LoadBalancer
    port: 5678
    annotations: {}

  ingress:
    enabled: true
    className: "traefik"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.certresolver: "le"
    hosts:
      - host: n8n.546digitalservices.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: n8n-tls
        hosts:
          - n8n.546digitalservices.com

  autoscaling:
    enabled: true # Você está sobrescrevendo via --set
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70

  persistence:
    enabled: true
    storageClass: "local-path" # Você está sobrescrevendo via --set
    size: "5Gi"                # Você está sobrescrevendo via --set

  podSecurityContext:
    fsGroup: 1000       # Você está sobrescrevendo via --set
    runAsUser: 1000     # Você está sobrescrevendo via --set
    runAsGroup: 1000    # Você está sobrescrevendo via --set
    runAsNonRoot: true  # Você está sobrescrevendo via --set

  initContainers:
    fixPermissions:
      enabled: false # Você está sobrescrevendo via --set
      image:
        repository: "busybox"
        tag: "1.36.1"

  livenessProbe:
    httpGet: { path: "/healthz", port: http }
    initialDelaySeconds: 120
    periodSeconds: 30
    timeoutSeconds: 15
    failureThreshold: 5

  readinessProbe:
    httpGet: { path: "/healthz", port: http }
    initialDelaySeconds: 60
    periodSeconds: 15
    timeoutSeconds: 10
    failureThreshold: 5

  # Configurações para o n8n se conectar às dependências
  externalPostgresql:
    host: "{{ .Release.Name }}-postgresql" # Será resolvido para 'my-n8n-postgresql'
    port: 5432
    database: "n8ndb"   # Corresponde a postgresql.auth.database
    username: "n8nuser" # Corresponde a postgresql.auth.username
    existingSecret: "{{ .Release.Name }}-postgresql" # Secret criado pelo chart Bitnami PG
    passwordSecretKey: "postgresql-password" # Chave padrão no secret do Bitnami para a senha do usuário da app

  externalRedis:
    host: "{{ .Release.Name }}-redis-master" # Será resolvido para 'my-n8n-redis-master'
    port: 6379
    existingSecret: "{{ .Release.Name }}-redis" # Secret criado pelo chart Bitnami Redis
    passwordSecretKey: "redis-password" # Chave padrão no secret do Bitnami

# --- Configurações do subchart PostgreSQL (Bitnami) ---
postgresql:
  enabled: true # Você está sobrescrevendo via --set
  auth:
    username: "n8nuser"   # Corresponde a n8n.externalPostgresql.username
    password: "VhB1knK#2vgVkbnyyc%p%hB#aCx" # Senha para o usuário n8n no PG
    database: "n8ndb"     # Corresponde a n8n.externalPostgresql.database
  primary:
    persistence:
      enabled: true
      storageClass: "local-path" # Você está sobrescrevendo via --set
      size: "10Gi"               # Você está sobrescrevendo via --set

# --- Configurações do subchart Redis (Bitnami) ---
redis:
  enabled: true
  architecture: "standalone"
  auth:
    enabled: true
    password: "1B6kPmysGGoNBKnvGuueJ3222u1zYBOK" # Senha para o Redis
  master:
    persistence:
      enabled: false
  metrics:
    enabled: false