{{- $configMapValues := .Values.configMap | default dict -}}
{{- $configMapEnabled := $configMapValues.enabled | default false -}}

{{- if $configMapEnabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configMapValues.name | default (printf "%s-settings" (include "n8n.fullname" .)) }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
data:
  settings.json: |
    {{- $configMapValues.settings | default "{}" | nindent 4 }}
{{- end }}