apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "n8n.fullname" . }}-config
  labels:
    app: {{ include "n8n.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  # Esse arquivo settings.json será copiado para /home/node/.n8n/config/settings.json
  settings.json: |-
    {
      "encryptionKey": "{{ .Values.config.encryptionKey }}"
    }