{{- $persistenceValues := dict -}}
{{- if .Values.persistence }}
  {{- $persistenceValues = .Values.persistence -}}
{{- end -}}

# DEBUG: $persistenceValues is {{ $persistenceValues | typeOf }}
# DEBUG: $persistenceValues.enabled is {{ $persistenceValues.enabled | typeOf }} and value is {{ $persistenceValues.enabled }}


{{- if $persistenceValues.enabled }}
  {{- $storageClass := $persistenceValues.storageClass | default "" -}}
  {{- $accessModes := $persistenceValues.accessModes | default (list "ReadWriteOnce") -}}
  {{- $size := $persistenceValues.size | default "1Gi" -}}
  {{- $annotations := $persistenceValues.annotations | default dict -}}
  {{- $existingClaim := $persistenceValues.existingClaim | default "" -}}
  {{- $claimName := $existingClaim | default (printf "%s-pvc" (include "n8n.fullname" .)) -}}

  {{- if not $existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $claimName }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- $accessModes | toYaml | nindent 4 }}
  resources:
    requests:
      storage: {{ $size | quote }}
  {{- if $storageClass }}
    {{- if (eq "-" $storageClass) }}
  storageClassName: ""
    {{- else }}
  storageClassName: "{{ $storageClass }}"
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}