apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n.fullname" . }}-postgresql
  labels:
    app: {{ include "n8n.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      name: postgres
  selector:
    app: {{ include "n8n.name" . }}
    component: postgresql