{{- $config := .Values.config | default dict -}}
{{- $existingSecretName := $config.existingEncryptionKeySecret | default "" -}}
{{- $encryptionKeySecretKey := $config.encryptionKeySecretKey | default "n8n-encryption-key" -}}
{{- $providedEncryptionKey := $config.encryptionKey | default "" -}}

{{- if not $existingSecretName }}
  {{- /* Só cria um novo secret se um 'existingSecretName' não for fornecido */}}
  {{- $secretName := include "n8n.encryptionKeySecretName" . -}} {{/* Este helper precisa usar $config também */}}
  {{- $encryptionKeyValue := $providedEncryptionKey | default (randAlphaNum 32) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
data:
  {{ $encryptionKeySecretKey }}: {{ $encryptionKeyValue | b64enc | quote }}
{{- end }}