{{- if not .Values.config.existingEncryptionKeySecret }}
{{- $secretName := include "n8n.encryptionKeySecretName" . -}}
{{- $encryptionKey := .Values.config.encryptionKey | default (randAlphaNum 32) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.config.encryptionKeySecretKey | default "n8n-encryption-key" }}: {{ $encryptionKey | b64enc | quote }}
{{- end }}