{{- if .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n.fullname" . }}-debugsvc
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
  {{- /* Removido bloco de anotações temporariamente */}}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 5678 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "n8n.selectorLabels" . | nindent 4 }}
{{- else }}
# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "n8n.fullname" . }}-debugsvc-service-values-missing
# spec:
#   type: ClusterIP
#   ports:
#     - port: 1234
#       targetPort: 1234
#   selector:
#     app: fake
# Comentado para não gerar um serviço inválido, mas para indicar no log se o .Values.service está faltando
{{- end }}