apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n.fullname" . }}-service\ nentioned
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5678
      protocol: TCP
      name: http
  selector:
    app: {{ include "n8n.name" . }}